### ISSUE TITLE
Evercrypt C Library

### ISSUE THREAD

**Issue by franziskuskiefer** [hacl-star/hacl-star#374]
This issue is for tracking and discussing changes to the dist folder. 

After discussions with @msprotz the high level goal is as follows.

## Evercrypt library
The `dist` folder contains a set of C files that can be configured with `configure` and built with `make`.
The `configure` script selects the C files that are included in the library (e.g. `./configure -c89` to select the `c89` compatible code or `./configure -target  -target aarch64-none-linux-android` to cross-compile for Android ARM64).
This way we have a single way of building and using the evercrypt library.

## Evercrypt packages
For consumers that don't use the full evercrypt library but only cherrypick files there will be a `package` command that essentially recreates the different directories we currently have in `dist` from the consolidated set of files that'll be there.

## To Dos
- [ ] consolidate generation
  - [ ] define minimal subset of C files we generate (remove duplicates across all dist folders)
  - [ ] generate only these distinct C files
- [ ] write package script to generate old distributions
- [ ] improve `configure` and `Makefile`
  - [ ] allow building the different configurations from previous distributions (if needed)
  - [ ] add configurations and builds for all common build targets

**Comment by msprotz** [comment]
Is this still relevant @franziskuskiefer? Looks like it's handled properly now in hacl-packages

**Comment by franziskuskiefer** [comment]
Yep, I think hacl-packages has this covered. Closing this.
