### ISSUE TITLE
Improvements in HACL* for the Python PR

### ISSUE THREAD

**Issue by msprotz** [hacl-star/hacl-star#724]
For the Python PR (https://github.com/python/cpython/pull/99109) I manually tweaked many small details in order to generate the most compact code. Here is the list of these fixes, and how we should backport them upstream on the Low* code rather than hand-patching the generated C. This will also allow addressing one key review comment, namely the request for a script that can automatically refresh the "vendored" copy of HACL* in Python directly from this repo.

- [x] ~separate sha2_streaming into sha2_256_streaming and sha2_512_streaming (the former also contains 224, the latter also contains 384)~ NOT DOING FOR NOW
- [x] do not include types.h from these files -- they don't need any of those definitions --> fixed with a script, not easy to do actually
- [x] ditch sha2_update_224 -- it's a copy of update_256 and we have a lemma somewhere that these two are identical... if we want to be backwards-compatible, consider using `[@@ CPrologue "#define Hacl_Streaming_SHA2_256_update_224 Hacl_Streaming_SHA2_256_update_256"]` (optional) --> https://github.com/hacl-star/hacl-star/pull/725
- [x] tweak the streaming code so that it does not generate instances of Hacl_Impl_SHA2_Types_uint8_2p --> fixed in https://github.com/FStarLang/karamel/pull/314
- [x] tweak krml to avoid KRML_CHECK_SIZE in streaming --> fixed by https://github.com/FStarLang/karamel/pull/315
- [x] streaming should not need sha2_types --> fixed in https://github.com/FStarLang/karamel/pull/314
- [x] builtin, callconv.h are not needed -- move in krml the `#define inline __inline__` to a more widely-included header, such as target.h https://github.com/FStarLang/karamel/pull/320
- [x] find a way to trim down target.h from a script (I'd rather not break it up upstream)
- [x] expose a state copy operation in streaming functor (#750)
- [x] tweak bundling to fold the constants into the streaming file since from here on this will be our only header to expose SHA2 (#752)
- [x] ditch sha224_update and sha224_update_nblocks from Hacl.SHA2.Scalar32 --> #742, and same thing with 384 --> later

**Comment by msprotz** [comment]
I'm wondering if it's really worth splitting everything into two separate file for the 32-bit and 64-bit versions.

Pros:
- clients don't have to include 4 algorithms if they only want one
- minimizes Python PR

Cons:
- need to split Hacl.SHA2.Scalar32, Hacl.Impl.SHA2.Generic (for the constants), Hacl.Streaming.SHA2

I guess what I could do is update the Python PR to also implement the 64-bit hashes then it would justify including a single file with all four.

Thoughts? @franziskuskiefer @R1kM and perhaps @polubelova

**Comment by franziskuskiefer** [comment]
> I'm wondering if it's really worth splitting everything into two separate file for the 32-bit and 64-bit versions.

The additional work/complexity is certainly not great. But if a minimal distribution of algorithms or supporting low powered devices (like embedded, 32-bit devices) is a goal, it might be worth doing.

**Comment by msprotz** [comment]
All done! Thanks to everyone involved, especially @R1kM
